Repository Nota-NetsPresso/PyNetsPresso, pull requests merged in 2024-07, with the labels that each got.

#262 #261 Save paths in metadata as absolute paths
  netspresso/VERSION
  netspresso/benchmarker/v2/benchmarker.py
  netspresso/compressor/v2/compressor.py
  netspresso/converter/v2/converter.py
  netspresso/trainer/trainer.py
  netspresso/utils/file.py
Labels: enhancement

#266 #260 Adding error schema in metadata
  netspresso/benchmarker/v2/benchmarker.py
  netspresso/compressor/v2/compressor.py
  netspresso/converter/v2/converter.py
  netspresso/metadata/benchmarker.py
  netspresso/metadata/common.py
  netspresso/metadata/compressor.py
  netspresso/metadata/converter.py
  netspresso/metadata/trainer.py
  netspresso/trainer/trainer.py
Labels: enhancement

#267 Bump version(v1.7.1.b1)
  netspresso/VERSION
Labels: release

#271 #270 Set defalut value of project_name
  netspresso/trainer/trainer.py
Labels: enhancement

#274 #272 Add missing framework in benchmark metadata
  netspresso/clients/launcher/v2/schemas/task/benchmark/response_body.py
  netspresso/metadata/benchmarker.py
Labels: enhancement

#275 Bump version(v1.7.1.b2)
  netspresso/VERSION
Labels: release

#277 #276 Change logging_dir to output_dir
  netspresso/metadata/trainer.py
  netspresso/trainer/trainer.py
Labels: enhancement

#278 Bump version(v1.7.1.b3)
  netspresso/VERSION
Labels: release

#279 Fix compressor options
  netspresso/VERSION
  netspresso/clients/compressor/v2/schemas/compression/base.py
Labels: bug

#280 #273 removing the v1 module
  examples/compressor/v1/automatic_compression.py
  examples/compressor/v1/create_model.py
  examples/compressor/v1/manual_compression.py
  examples/compressor/v1/recommendation_compression.py
  examples/converter & benchmarker/v1/keras2tflite.py
  examples/converter & benchmarker/v1/keras2tflite_int8.py
  examples/converter & benchmarker/v1/onnx2drpai.py
  examples/converter & benchmarker/v1/onnx2openvino.py
  examples/converter & benchmarker/v1/onnx2tensorrt.py
  examples/converter & benchmarker/v1/onnx2tflite.py
  examples/converter & benchmarker/v1/onnx2tflite_int8.py
  netspresso/benchmarker/__init__.py
  netspresso/benchmarker/v1/__init__.py
  netspresso/benchmarker/v1/benchmarker.py
  netspresso/clients/auth/client.py
  netspresso/clients/auth/v1/__init__.py
  netspresso/clients/auth/v1/client.py
  netspresso/clients/auth/v1/schemas/__init__.py
  netspresso/clients/auth/v1/schemas/auth.py
  netspresso/clients/compressor/__init__.py
  netspresso/clients/compressor/v1/__init__.py
  netspresso/clients/compressor/v1/main.py
  netspresso/clients/compressor/v1/schemas/__init__.py
  netspresso/clients/compressor/v1/schemas/compression.py
  netspresso/clients/compressor/v1/schemas/model.py
  netspresso/clients/config.py
  netspresso/clients/configs/config-v1-prod.ini
  netspresso/clients/launcher/__init__.py
  netspresso/clients/launcher/v1/__init__.py
  netspresso/clients/launcher/v1/main.py
  netspresso/clients/launcher/v1/schemas/__init__.py
  netspresso/clients/launcher/v1/schemas/model.py
  netspresso/compressor/__init__.py
  netspresso/compressor/v1/__init__.py
  netspresso/compressor/v1/compressor.py
  netspresso/converter/__init__.py
  netspresso/converter/v1/__init__.py
  netspresso/converter/v1/converter.py
  netspresso/enums/__init__.py
  netspresso/netspresso.py
Labels: enhancement

#283 #281 Remove the backward option of the policy options
  docs/description/api/compressor/compress/advanced_compression/pruning_options.rst
  netspresso/enums/compression.py
Labels: enhancement

#285 #284 Remove pydantic library
  OOS_NOTICE
  requirements.txt
Labels: enhancement

#287 #286 Modified the request_body from model_dump() to asdict()
  netspresso/clients/auth/v2/client.py
Labels: bug

#288 #246 Fix log same comments in multiple lines
  netspresso/clients/auth/v2/client.py
  netspresso/clients/config.py
Labels: bug, enhancement

#291 #290 Fix reissue access token
  netspresso/benchmarker/v2/benchmarker.py
  netspresso/converter/v2/converter.py
  netspresso/metadata/common.py
  netspresso/trainer/trainer.py
  netspresso/utils/file.py
Labels: bug

#292 #282 Add a progress bar to show progress during upload
  netspresso/clients/compressor/v2/main.py
  netspresso/clients/launcher/v2/implements/model/model.py
  netspresso/clients/utils/common.py
  requirements.txt
Labels: enhancement

#296 #295 Refactor configuration to use environment variables for HOST and PORT
  netspresso/clients/auth/client.py
  netspresso/clients/config.py
  netspresso/clients/configs/config-v2-prod-cloud.ini
  requirements.txt
Labels: enhancement

#299 #298 Fix model.name to model_name
  netspresso/trainer/trainer.py
Labels: enhancement

#301 #300 Updated code to search for files matching both `*best_fx.pt` and `*best.pt` patterns
  netspresso/trainer/trainer.py
Labels: bug

#294 #293 Add Structured Neuron-level Pruning (SNP) method
  docs/_static/compression/methods/pruning_snp.png
  docs/description/api/compressor/compress/advanced_compression/compression_method.rst
  docs/description/api/compressor/compress/advanced_compression/manual_compression.rst
  docs/description/api/compressor/compress/advanced_compression/pruning_options.rst
  docs/description/api/compressor/compress/advanced_compression/recommendation_compression.rst
  docs/description/api/compressor/compress/automatic_compression.rst
  netspresso/compressor/v2/compressor.py
  netspresso/enums/compression.py
Labels: enhancement

#289 #268 Integrate Qualcomm AI Hub
  examples/qai_hub/compile_pytorch2tflite.py
  netspresso/__init__.py
  netspresso/inferencer/__init__.py
  netspresso/inferencer/postprocessors/__init__.py
  netspresso/inferencer/postprocessors/detection.py
  netspresso/inferencer/preprocessors/__init__.py
  netspresso/inferencer/preprocessors/base.py
  netspresso/inferencer/visualizers/__init__.py
  netspresso/inferencer/visualizers/detection.py
  netspresso/metadata/benchmarker.py
  netspresso/netspresso.py
  netspresso/qai_hub/__init__.py
  netspresso/qai_hub/base.py
  netspresso/qai_hub/benchmarker.py
  netspresso/qai_hub/converter.py
  netspresso/qai_hub/options/__init__.py
  netspresso/qai_hub/options/common.py
  netspresso/qai_hub/options/compile.py
  netspresso/qai_hub/options/profile.py
  netspresso/trainer/trainer.py
  netspresso/utils/plotter.py
  requirements.txt
Labels: enhancement

#305 #304 Add model_name definition in initialize_from_yaml function
  netspresso/trainer/trainer.py
Labels: bug

#308 #307 Update self.tokens after login to ensure token refresh
  netspresso/clients/auth/client.py
Labels: enhancement

#309 #297 Update task error log for launcher
  netspresso/benchmarker/v2/benchmarker.py
  netspresso/clients/launcher/v2/schemas/task/benchmark/response_body.py
  netspresso/clients/launcher/v2/schemas/task/convert/response_body.py
  netspresso/converter/v2/converter.py
Labels: enhancement

#311 #306 Add onnx to dlc convert & Samsung Galaxy S24 Ultra device
  examples/converter & benchmarker/v2/onnx2dlc.py
  netspresso/enums/device.py
  netspresso/enums/model.py
  netspresso/utils/file.py
Labels: enhancement
